[tool.poetry]
name = "pycountrycode"
version = "0.1.0"
description = ""
authors = ["Vincent Arel-Bundock <vincent.arel-bundock@umontreal.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
