[tool.poetry]
name = "countrycode"
version = "0.3.0"
description = ""
authors = ["Vincent Arel-Bundock <vincent.arel-bundock@umontreal.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
polars = "^0.18.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
